# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: Armadito REST API

host: localhost:8888
basePath: /api
produces:
  - application/json

# Describe your paths here
paths:

  /register:
    get:
      description: |
        register an API client |
        this will return an API token
      produces:
        - application/json
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/Token'
        default:
          description: error
          schema:
            $ref: '#/definitions/Error'

  /unregister:
    get:
      description: |
        unregister an API client
      produces:
        - application/json
      parameters:
        - in: header
          name: X-Armadito-Token
          description: session token
          required: true
          type: string
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/Token'
        default:
          description: error
          schema:
            $ref: '#/definitions/Error'

  /ping:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Ping the server to get status
      # This is array of GET operation parameters:
      # Expected responses for this operation:
      produces:
        - application/json
      parameters:
        - in: header
          name: X-Armadito-Token
          description: session token
          required: true
          type: integer
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            $ref: '#/definitions/Pong'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /event:
    get:
      description:
        get server event
      produces:
        - application/json
      parameters:
        - in: header
          name: X-Armadito-Token
          description: session token
          required: true
          type: integer
      responses:
        200:
          description: event received OK
          schema:
            $ref: '#/definitions/Event'

  /scan:
    post:
      summary: launch a scan
      description: launch a scan
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: X-Armadito-Token
          description: session token
          required: true
          type: integer
        - in: body
          name: body
          description: scan object
          required: true
          schema:
            $ref: "#/definitions/Scan"
      responses:
        200:
          description: OK
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /status:
    get:
      description:
        get the server status
      produces:
        - application/json
      parameters:
        - in: header
          name: X-Armadito-Token
          description: session token
          required: true
          type: integer
      responses:
        200:
          description: OK
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

  Token:
    type: object
    properties:
      token:
        type: integer
        format: int64
    
  Pong:
    type: object
    properties:
      status:
        type: string
        description: contains the server status
        enum: 
          - "ok"

  Scan:
    type: object
    properties:
      path:
        type: string
        description: the path to scan
  
  Event:
    type: object
    discriminator: event_type
    required:
      - event_type # required for inheritance to work
    properties:
      event_type:
        type: string

  ScanStatus:
    type: string
    enum: 
      - "undecided"
      - "clean"
      - "ignored"
      - "invalid argument"
      - "internal error"
      - "suspicious"
      - "white listed"
      - "malware"
      - "unknown status"
    description: scan status for path

  DetectionEvent:
    allOf:
      - $ref: '#/definitions/Event'
      - type: object
        properties:
          detection_time:
            type: string
            format: dateTime
            description: detection timestamp
          context:
            type: string
            enum:
              - "real-time"
              - "on-demand"
          path:
            type: string
            description: path
          scan_status:
            $ref: '#/definitions/ScanStatus'
          scan_action:
            type: string
            description: action taken for malware
          module_name:
            type: string
            description: name of scan module that has detected the malware
          module_report:
            type: string
            description: report of scan module that has detected the malware

  OnDemandProgressEvent:
    allOf:
      - $ref: '#/definitions/Event'
      - type: object
        properties:
          progress:
            type: integer
            format: int32
            description: the progress bar
          malware_count:
            type: integer
            format: int32
            description: malware counter
          suspicious_count:
            type: integer
            format: int32
            description: suspicious counter
          scanned_count:
            type: integer
            format: int32
            description: scanned file counter

  OnDemandCompletedEvent:
    allOf:
      - $ref: '#/definitions/Event'
      - type: object
        properties:
          start_time:
            type: string
            format: dateTime
            description: start time of the on-demand scan
          duration:
            type: string
            format: dateTime
            description: duration of the scan
          total_malware_count:
            type: integer
            format: int32
            description: malware counter
          total_suspicious_count:
            type: integer
            format: int32
            description: suspicious counter
          total_scanned_count:
            type: integer
            format: int32
            description: scanned file counter
          # array of detection event

  UpdateStatus:
    type: string
    enum:
      - "up-to-date"
      - "late"
      - "critical"
      - "non-available"
    description: update status of modules and antivirus

  BaseInfo:
    type: object
    properties:
      name:
        type: string
        description: base name
      base_update_timestamp:
        type: integer
        format: int64
        description: base update timestamp
      version:
        type: string
        description: base version if available
      signature_count:
        type: integer
        description: number of signatures in the base
      full_path:
        type: string
        description: full path of the base file if available

  ModuleStatus:
    type: object
    properties:
      name:
        type: string
        description: module name
      mod_status:
        $ref: '#/definitions/UpdateStatus'
      mod_update_timestamp:
        type: integer
        format: int64
        description: module update timestamp
      bases:
        type: array
        items:
          $ref: '#/definitions/BaseInfo'

  StatusEvent:
    allOf:
      - $ref: '#/definitions/Event'
      - type: object
        properties:
          global_status:
            $ref: '#/definitions/UpdateStatus'
          global_update_timestamp:
            type: integer
            format: int64
            description: global update timestamp
          modules:
            type: array
            items:
              $ref: '#/definitions/ModuleStatus'

  #
  # not implemented yet
  #
  AntivirusStatus:
    type: object
    properties:
      version:
        type: string
        description: the version of the antivirus
      service:
        type: boolean
        description: is the service on or off?
      real-time-protection:
        type: boolean
        description: is the real-time protection on or off?

